### ISSUE TITLE
Release 1.1.3 to maven central

### ISSUE THREAD

**Issue by eduardbosch** [DroidsOnRoids/mockwebserver-path-dispatcher#26]
Hi @koral-- 

¿Can you release the `1.1.3` version to maven central?
The latest one is the `1.1.2`

Jitpack cannot create a version https://jitpack.io/#DroidsOnRoids/mockwebserver-path-dispatcher/1.1.3

Thanks 🙂

**Comment by koral--** [comment]
Thanks for spotting that!
It looks like automated maven staging repo closing and releasing failed this time.
Should be available on maven central in a few hours.
