### ISSUE TITLE
1.1.5 not available on Maven Central

### ISSUE THREAD

**Issue by eduardbosch-jt** [DroidsOnRoids/mockwebserver-path-dispatcher#33]
Hi @koral-- 

I've been checking the 1.1.5 version but does not appear on maven central.
Do you know if there was any problem with the release?
Normally, it does not take much time to appear online.

Many thanks 🙂

**Comment by koral--** [comment]
Thanks for spotting that. Indeed the process hung at the staging repo closing step. I've just moved it forward and confirmed that the release step was successful.
That version should be propagated within 2 hours to all the maven central mirrors.
